# Generated by Django 3.1b1 on 2020-06-27 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purr',
            name='content',
            field=models.TextField(max_length=140),
        ),
    ]
