steps:
    - id: 'build  '
      name: 'gcr.io/cloud-builders/docker'
      args: ['build', '-t', 'gcr.io/${PROJECT_ID}/${_SERVICE}', '.']
    - id: 'push   '
      name: 'gcr.io/cloud-builders/docker'
      args: ['push', 'gcr.io/${PROJECT_ID}/${_SERVICE}']
    - id: 'migrate'
      name: 'gcr.io/${PROJECT_ID}/${_SERVICE}'
      args: ['sh', '.cloudbuild/django_migrate.sh']
    - id: 'deploy '
      name: 'gcr.io/cloud-builders/gcloud'
      args: ["run", "deploy", "${_SERVICE}",
            "--platform", "managed",
            "--region", "${_REGION}",
            "--image", "gcr.io/$PROJECT_ID/${_SERVICE}"]

substitutions:
    _SERVICE: mewgram
    _REGION: us-east1
